package com.webxert.attrixstudent.model;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.List;

/**
 * Created by hp on 12/17/2018.
 */

public class ClassModel implements Parcelable {
    String course_id;
    String course_name;

    protected ClassModel(Parcel in) {
        course_id = in.readString();
        course_name = in.readString();
        classKey = in.readString();
        isRegister = in.readByte() != 0;
        courseNo = in.readString();
        enrolledStudents = in.createStringArrayList();
        classId = in.readString();
        teacherId = in.readString();
        title = in.readString();
        classCode = in.readString();
    }

    public static final Creator<ClassModel> CREATOR = new Creator<ClassModel>() {
        @Override
        public ClassModel createFromParcel(Parcel in) {
            return new ClassModel(in);
        }

        @Override
        public ClassModel[] newArray(int size) {
            return new ClassModel[size];
        }
    };

    public String getClassKey() {
        return classKey;
    }

    public void setClassKey(String classKey) {
        this.classKey = classKey;
    }

    private String classKey; //generated by firebase
    boolean isRegister;
    private String courseNo;
    private List<String> enrolledStudents;
    private String classId; //generated for business logic
    private String teacherId;
    private String title;
    private String classCode;

    public String getClassCode() {
        return classCode;
    }

    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    @Override
    public int describeContents() {
     return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(course_id);
        parcel.writeString(course_name);
        parcel.writeString(classKey);
        parcel.writeByte((byte) (isRegister ? 1 : 0));
        parcel.writeString(courseNo);
        parcel.writeStringList(enrolledStudents);
        parcel.writeString(classId);
        parcel.writeString(teacherId);
        parcel.writeString(title);
        parcel.writeString(classCode);
    }

    public String getCourseNo() {
        return courseNo;
    }

    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo;
    }

    public List<String> getEnrolledStudents() {
        return enrolledStudents;
    }

    public void setEnrolledStudents(List<String> enrolledStudents) {
        this.enrolledStudents = enrolledStudents;
    }

    public String getClassId() {
        return classId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ClassModel(String course_id, String course_name, boolean isRegister) {
        this.course_id = course_id;
        this.course_name = course_name;
        this.isRegister = isRegister;
    }

    public ClassModel() {
    }

    public String getCourse_id() {
        return course_id;
    }

    public void setCourse_id(String course_id) {
        this.course_id = course_id;
    }

    public String getCourse_name() {
        return course_name;
    }

    public void setCourse_name(String course_name) {
        this.course_name = course_name;
    }

    public boolean isRegister() {
        return isRegister;
    }

    public void setRegister(boolean register) {
        isRegister = register;
    }

}
